name: Docker Image Create & Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
       docker build -t test-storage .
       
    - name: Push Docker Image to Docker Hub
      run: |
       docker tag hello-world "${{ secrets.DOCKER_USERNAME_SAI40 }}"/test-storage
       echo "${{ secrets.DOCKER_PASSWORD_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME_SAI40 }}" --password-stdin
       docker push "${{ secrets.DOCKER_USERNAME_SAI40 }}"/test-storage
       
       
